vim.cmd("hi clear")
vim.opt.termguicolors = true
vim.g.colors_name = "dark-custom"

-- COLORES BASE
local c = {
  bg = "#1A1B1D",
  bg_alt = "#222222",
  bg_lite = "#2A2D31",
  bg_dark = "#17191A",
  fg = "#E8E8EC",
  fg_lite = "#F0F0F5",
  fg_dim = "#9090A0",
  fg_mute = "#808090",
  red = "#FF6B6B",
  green = "#98D982",
  yellow = "#F0D97D",
  blue = "#6BB8FF",
  purple = "#BB8EFF",
  pink = "#FF85CC",
  orange = "#F0A060",
  cyan = "#70D8C0",
  comment = "#606070",
  selection = "#354060",
  cursor_line = "#282830",
  line_nr = "#606070",
  border = "#404050",
}

vim.api.nvim_set_hl(0, "Normal", { bg = c.bg, fg = c.fg })
vim.api.nvim_set_hl(0, "NormalNC", { bg = c.bg, fg = c.fg_dim })
vim.api.nvim_set_hl(0, "NormalFloat", { bg = c.bg_alt, fg = c.fg })
vim.api.nvim_set_hl(0, "FloatBorder", { bg = c.bg_alt, fg = c.border })
vim.api.nvim_set_hl(0, "Cursor", { fg = c.bg, bg = "#FFFFFF" })
vim.api.nvim_set_hl(0, "CursorLine", { bg = c.cursor_line })
vim.api.nvim_set_hl(0, "CursorLineNr", { fg = c.fg })
vim.api.nvim_set_hl(0, "LineNr", { fg = c.fg_mute })
vim.api.nvim_set_hl(0, "Folded", { bg = c.bg_alt, fg = c.fg_mute })
vim.api.nvim_set_hl(0, "FoldColumn", { bg = c.bg, fg = c.fg_mute })
vim.api.nvim_set_hl(0, "Comment", { fg = c.fg_mute, italic = true })
vim.api.nvim_set_hl(0, "SpecialComment", { fg = c.fg_mute })
vim.api.nvim_set_hl(0, "Todo", { fg = c.orange, bold = true })
vim.api.nvim_set_hl(0, "String", { fg = c.green })
vim.api.nvim_set_hl(0, "Constant", { fg = c.cyan })
vim.api.nvim_set_hl(0, "Number", { fg = c.pink })
vim.api.nvim_set_hl(0, "Boolean", { fg = c.pink })
vim.api.nvim_set_hl(0, "Float", { fg = c.pink })
vim.api.nvim_set_hl(0, "Keyword", { fg = c.purple })
vim.api.nvim_set_hl(0, "Statement", { fg = c.purple })
vim.api.nvim_set_hl(0, "Conditional", { fg = c.purple })
vim.api.nvim_set_hl(0, "Repeat", { fg = c.purple })
vim.api.nvim_set_hl(0, "Label", { fg = c.purple })
vim.api.nvim_set_hl(0, "Operator", { fg = c.fg })
vim.api.nvim_set_hl(0, "StorageClass", { fg = c.purple })
vim.api.nvim_set_hl(0, "Function", { fg = c.blue })
vim.api.nvim_set_hl(0, "Method", { fg = c.blue })
vim.api.nvim_set_hl(0, "Type", { fg = c.yellow })
vim.api.nvim_set_hl(0, "TypeDef", { fg = c.yellow })
vim.api.nvim_set_hl(0, "Class", { fg = c.yellow })
vim.api.nvim_set_hl(0, "Struct", { fg = c.yellow })
vim.api.nvim_set_hl(0, "Variable", { fg = c.fg })
vim.api.nvim_set_hl(0, "Identifier", { fg = c.fg })
vim.api.nvim_set_hl(0, "Tag", { fg = c.red })
vim.api.nvim_set_hl(0, "htmlTag", { fg = c.red })
vim.api.nvim_set_hl(0, "htmlTagName", { fg = c.red })
vim.api.nvim_set_hl(0, "htmlArg", { fg = c.yellow })
vim.api.nvim_set_hl(0, "Attribute", { fg = c.yellow })
vim.api.nvim_set_hl(0, "Error", { fg = c.red })
vim.api.nvim_set_hl(0, "ErrorMsg", { fg = c.red })
vim.api.nvim_set_hl(0, "WarningMsg", { fg = c.orange })
vim.api.nvim_set_hl(0, "DiagnosticError", { fg = c.red })
vim.api.nvim_set_hl(0, "DiagnosticWarn", { fg = c.orange })
vim.api.nvim_set_hl(0, "DiagnosticInfo", { fg = c.blue })
vim.api.nvim_set_hl(0, "DiagnosticHint", { fg = c.green })
vim.api.nvim_set_hl(0, "Search", { bg = c.selection })
vim.api.nvim_set_hl(0, "IncSearch", { bg = "#355080" })
vim.api.nvim_set_hl(0, "MatchParen", { bg = c.selection, bold = true })
vim.api.nvim_set_hl(0, "Delimiter", { fg = c.fg_dim })
vim.api.nvim_set_hl(0, "SpecialChar", { fg = c.orange })
vim.api.nvim_set_hl(0, "PreProc", { fg = c.blue })
vim.api.nvim_set_hl(0, "Include", { fg = c.purple })
vim.api.nvim_set_hl(0, "Define", { fg = c.purple })
vim.api.nvim_set_hl(0, "markdownHeading", { fg = c.blue, bold = true })
vim.api.nvim_set_hl(0, "markdownCode", { fg = c.green })
vim.api.nvim_set_hl(0, "markdownLinkText", { fg = c.blue })
vim.api.nvim_set_hl(0, "WinBar", { bg = c.bg_alt, fg = c.fg })
vim.api.nvim_set_hl(0, "WinBarNC", { bg = c.bg_alt, fg = c.fg_mute })
vim.api.nvim_set_hl(0, "VertSplit", { bg = c.bg_alt, fg = c.border })
vim.api.nvim_set_hl(0, "WinSeparator", { bg = c.bg_alt, fg = c.border })
vim.api.nvim_set_hl(0, "StatusLine", { bg = c.bg_alt, fg = c.fg })
vim.api.nvim_set_hl(0, "StatusLineNC", { bg = c.bg_alt, fg = c.fg_mute })
vim.api.nvim_set_hl(0, "TelescopeNormal", { bg = c.bg_alt, fg = c.fg })
vim.api.nvim_set_hl(0, "TelescopeBorder", { bg = c.bg_alt, fg = c.border })
vim.api.nvim_set_hl(0, "TelescopeTitle", { bg = c.bg_alt, fg = c.fg, bold = true })
vim.api.nvim_set_hl(0, "TelescopePromptNormal", { bg = c.bg_alt, fg = c.fg })
vim.api.nvim_set_hl(0, "TelescopePromptBorder", { bg = c.bg_alt, fg = c.border })
vim.api.nvim_set_hl(0, "TelescopePromptTitle", { bg = c.bg_alt, fg = c.fg })
vim.api.nvim_set_hl(0, "TelescopePromptPrefix", { bg = c.bg_alt, fg = c.blue })
vim.api.nvim_set_hl(0, "TelescopePreviewNormal", { bg = c.bg, fg = c.fg })
vim.api.nvim_set_hl(0, "TelescopePreviewBorder", { bg = c.bg, fg = c.border })
vim.api.nvim_set_hl(0, "TelescopeResultsNormal", { bg = c.bg_alt, fg = c.fg })
vim.api.nvim_set_hl(0, "TelescopeResultsBorder", { bg = c.bg_alt, fg = c.border })
vim.api.nvim_set_hl(0, "TelescopeSelection", { bg = c.selection, fg = c.fg })
vim.api.nvim_set_hl(0, "TelescopeSelectionCaret", { fg = c.blue })
vim.api.nvim_set_hl(0, "TelescopeMatching", { fg = c.green, bold = true })
vim.api.nvim_set_hl(0, "TelescopeResultsFileDevIcon", { fg = c.cyan })
-- Directorios visibles
vim.api.nvim_set_hl(0, "TelescopeResultsPath", { fg = c.fg_dim })
vim.api.nvim_set_hl(0, "TelescopeResultsFunction", { fg = c.blue })
vim.api.nvim_set_hl(0, "TelescopeResultsIdentifier", { fg = c.purple })
vim.api.nvim_set_hl(0, "TelescopeResultsLineNr", { fg = c.fg_mute })
vim.api.nvim_set_hl(0, "TelescopeResultsNumber", { fg = c.pink })
vim.api.nvim_set_hl(0, "TelescopeResultsString", { fg = c.green })
vim.api.nvim_set_hl(0, "TelescopeResultsType", { fg = c.yellow })
vim.api.nvim_set_hl(0, "TelescopeResultsComment", { fg = c.fg_mute })
vim.api.nvim_set_hl(0, "TelescopeResultsSpecialComment", { fg = c.fg_mute })
vim.api.nvim_set_hl(0, "TelescopeResultsMarkdownH1", { fg = c.blue, bold = true })
vim.api.nvim_set_hl(0, "TelescopeResultsMarkdownH2", { fg = c.blue })
vim.api.nvim_set_hl(0, "TelescopeResultsMarkdownH3", { fg = c.cyan })
vim.api.nvim_set_hl(0, "TelescopeResultsMarkdownLink", { fg = c.cyan })
vim.api.nvim_set_hl(0, "TelescopePreviewChar", { fg = c.fg_mute })
vim.api.nvim_set_hl(0, "TelescopePreviewDate", { fg = c.cyan })
vim.api.nvim_set_hl(0, "TelescopePreviewExecute", { fg = c.purple })
vim.api.nvim_set_hl(0, "TelescopePreviewGroup", { fg = c.purple })
vim.api.nvim_set_hl(0, "TelescopePreviewHead", { fg = c.blue })
vim.api.nvim_set_hl(0, "TelescopePreviewLine", { fg = c.fg })
vim.api.nvim_set_hl(0, "TelescopePreviewLink", { fg = c.cyan })
vim.api.nvim_set_hl(0, "TelescopePreviewMatch", { fg = c.orange })
vim.api.nvim_set_hl(0, "TelescopePreviewMessage", { fg = c.fg })
vim.api.nvim_set_hl(0, "TelescopePreviewMessageBackground", { bg = c.bg_lite })
vim.api.nvim_set_hl(0, "TelescopePreviewMeta", { fg = c.purple })
vim.api.nvim_set_hl(0, "TelescopePreviewNormal", { bg = c.bg, fg = c.fg })
vim.api.nvim_set_hl(0, "TelescopePreviewBorder", { bg = c.bg, fg = c.border })
vim.api.nvim_set_hl(0, "TelescopePreviewTitle", { fg = c.fg, bold = true })
-- Telescope Dropdown
vim.api.nvim_set_hl(0, "TelescopeDropdownNormal", { bg = c.bg_alt, fg = c.fg })
vim.api.nvim_set_hl(0, "TelescopeDropdownBorder", { bg = c.bg_alt, fg = c.border })
vim.api.nvim_set_hl(0, "TelescopeDropdownTitle", { bg = c.bg_alt, fg = c.fg, bold = true })
vim.api.nvim_set_hl(0, "TelescopeDropdownSelection", { bg = c.selection, fg = c.fg })
vim.api.nvim_set_hl(0, "TelescopeDropdownSelectionCaret", { fg = c.blue })
vim.api.nvim_set_hl(0, "TelescopePreviewTelescopeNormal", { bg = c.bg, fg = c.fg })
vim.api.nvim_set_hl(0, "TelescopePreviewTelescopeBorder", { bg = c.bg, fg = c.border })
vim.api.nvim_set_hl(0, "LspReferenceText", { bg = c.selection })
vim.api.nvim_set_hl(0, "LspReferenceRead", { bg = c.selection })
vim.api.nvim_set_hl(0, "LspReferenceWrite", { bg = c.selection })
vim.api.nvim_set_hl(0, "DiffAdd", { bg = "#1a3a25" })
vim.api.nvim_set_hl(0, "DiffChange", { bg = "#1a2a3a" })
vim.api.nvim_set_hl(0, "DiffDelete", { bg = "#3a1a1a" })
vim.api.nvim_set_hl(0, "DiffText", { bg = "#1a3a25" })
vim.api.nvim_set_hl(0, "GitSignsAdd", { fg = c.green })
vim.api.nvim_set_hl(0, "GitSignsChange", { fg = c.blue })
vim.api.nvim_set_hl(0, "GitSignsDelete", { fg = c.red })
vim.api.nvim_set_hl(0, "Visual", { bg = c.selection })
vim.api.nvim_set_hl(0, "VisualNOS", { bg = c.selection })
vim.api.nvim_set_hl(0, "WhichKey", { fg = c.blue })
vim.api.nvim_set_hl(0, "WhichKeyGroup", { fg = c.yellow })
vim.api.nvim_set_hl(0, "WhichKeyDesc", { fg = c.fg })
vim.api.nvim_set_hl(0, "WhichKeyFloat", { bg = c.bg_alt })
vim.api.nvim_set_hl(0, "NoiceCmdlinePopup", { bg = c.bg_alt, fg = c.fg })
vim.api.nvim_set_hl(0, "NoiceCmdlinePopupBorder", { bg = c.bg_alt, fg = c.border })
vim.api.nvim_set_hl(0, "NoicePopupmenu", { bg = c.bg_alt, fg = c.fg })
vim.api.nvim_set_hl(0, "NoicePopupmenuBorder", { bg = c.bg_alt, fg = c.border })
vim.api.nvim_set_hl(0, "NoicePopupmenuSelected", { bg = c.selection, fg = c.fg })
vim.api.nvim_set_hl(0, "NoicePopupmenuKind", { fg = c.blue })
vim.api.nvim_set_hl(0, "NeoTreeNormal", { bg = c.bg, fg = c.fg })
vim.api.nvim_set_hl(0, "NeoTreeNormalNC", { bg = c.bg_alt, fg = c.fg_dim })
vim.api.nvim_set_hl(0, "NeoTreeFloatNormal", { bg = c.bg_alt, fg = c.fg })
vim.api.nvim_set_hl(0, "NeoTreeFloatBorder", { bg = c.bg_alt, fg = c.border })
vim.api.nvim_set_hl(0, "NeoTreeFileName", { fg = c.fg })
vim.api.nvim_set_hl(0, "NeoTreeFileNameOpened", { fg = c.fg })
vim.api.nvim_set_hl(0, "NeoTreeDirectoryIcon", { fg = c.blue })
vim.api.nvim_set_hl(0, "NeoTreeRootName", { fg = c.fg, bold = true })
vim.api.nvim_set_hl(0, "NeoTreeIndentMarker", { fg = c.border })
vim.api.nvim_set_hl(0, "MiniIndentscopeSymbol", { fg = c.border })
vim.api.nvim_set_hl(0, "MiniPickNormal", { bg = c.bg_alt, fg = c.fg })
vim.api.nvim_set_hl(0, "MiniPickBorder", { bg = c.bg_alt, fg = c.border })
vim.api.nvim_set_hl(0, "MiniPickHeader", { fg = c.blue })
vim.api.nvim_set_hl(0, "MiniPickMatchText", { bg = c.selection })
vim.api.nvim_set_hl(0, "TSAnnotation", { fg = c.orange })
vim.api.nvim_set_hl(0, "TSAttribute", { fg = c.yellow })
vim.api.nvim_set_hl(0, "TSBoolean", { fg = c.pink })
vim.api.nvim_set_hl(0, "TSCharacter", { fg = c.green })
vim.api.nvim_set_hl(0, "TSComment", { fg = c.fg_mute, italic = true })
vim.api.nvim_set_hl(0, "TSConditional", { fg = c.purple })
vim.api.nvim_set_hl(0, "TSConstructor", { fg = c.yellow })
vim.api.nvim_set_hl(0, "TSConstant", { fg = c.cyan })
vim.api.nvim_set_hl(0, "TSConstBuiltin", { fg = c.cyan })
vim.api.nvim_set_hl(0, "TSError", { fg = c.red })
vim.api.nvim_set_hl(0, "TSException", { fg = c.red })
vim.api.nvim_set_hl(0, "TSField", { fg = c.fg })
vim.api.nvim_set_hl(0, "TSFloat", { fg = c.pink })
vim.api.nvim_set_hl(0, "TSFunction", { fg = c.blue })
vim.api.nvim_set_hl(0, "TSFuncBuiltin", { fg = c.blue })
vim.api.nvim_set_hl(0, "TSInclude", { fg = c.purple })
vim.api.nvim_set_hl(0, "TSKeyword", { fg = c.purple })
vim.api.nvim_set_hl(0, "TSKeywordFunction", { fg = c.purple })
vim.api.nvim_set_hl(0, "TSLabel", { fg = c.purple })
vim.api.nvim_set_hl(0, "TSMethod", { fg = c.blue })
vim.api.nvim_set_hl(0, "TSNamespace", { fg = c.yellow })
vim.api.nvim_set_hl(0, "TSNumber", { fg = c.pink })
vim.api.nvim_set_hl(0, "TSOperator", { fg = c.fg })
vim.api.nvim_set_hl(0, "TSParameter", { fg = c.fg })
vim.api.nvim_set_hl(0, "TSProperty", { fg = c.fg })
vim.api.nvim_set_hl(0, "TSPunctBracket", { fg = c.fg_dim })
vim.api.nvim_set_hl(0, "TSPunctDelimiter", { fg = c.fg_dim })
vim.api.nvim_set_hl(0, "TSRepeat", { fg = c.purple })
vim.api.nvim_set_hl(0, "TSStorageClass", { fg = c.purple })
vim.api.nvim_set_hl(0, "TSString", { fg = c.green })
vim.api.nvim_set_hl(0, "TSStringEscape", { fg = c.cyan })
vim.api.nvim_set_hl(0, "TSTag", { fg = c.red })
vim.api.nvim_set_hl(0, "TSTagDelimiter", { fg = c.fg_dim })
vim.api.nvim_set_hl(0, "TSText", { fg = c.fg })
vim.api.nvim_set_hl(0, "TSTodo", { fg = c.orange, bold = true })
vim.api.nvim_set_hl(0, "TSType", { fg = c.yellow })
vim.api.nvim_set_hl(0, "TSTypeBuiltin", { fg = c.yellow })
vim.api.nvim_set_hl(0, "TSURI", { fg = c.cyan, underline = true })
vim.api.nvim_set_hl(0, "TSVariable", { fg = c.fg })
vim.api.nvim_set_hl(0, "TSVariableBuiltin", { fg = c.cyan })
vim.api.nvim_set_hl(0, "RainbowRed", { fg = c.red })
vim.api.nvim_set_hl(0, "RainbowYellow", { fg = c.yellow })
vim.api.nvim_set_hl(0, "RainbowBlue", { fg = c.blue })
vim.api.nvim_set_hl(0, "RainbowOrange", { fg = c.pink })
vim.api.nvim_set_hl(0, "RainbowGreen", { fg = c.green })
vim.api.nvim_set_hl(0, "RainbowViolet", { fg = c.purple })
vim.api.nvim_set_hl(0, "RainbowCyan", { fg = c.cyan })
vim.api.nvim_set_hl(0, "Pmenu", { bg = c.bg_alt, fg = c.fg })
vim.api.nvim_set_hl(0, "PmenuSel", { bg = c.selection, fg = c.fg })
vim.api.nvim_set_hl(0, "PmenuSbar", { bg = c.bg_alt })
vim.api.nvim_set_hl(0, "PmenuThumb", { bg = c.border })
vim.api.nvim_set_hl(0, "PmenuKind", { fg = c.blue })
vim.api.nvim_set_hl(0, "PmenuKindText", { fg = c.green })
vim.api.nvim_set_hl(0, "PmenuKindKeyword", { fg = c.purple })
vim.api.nvim_set_hl(0, "PmenuKindFunction", { fg = c.blue })
vim.api.nvim_set_hl(0, "PmenuKindClass", { fg = c.yellow })
vim.api.nvim_set_hl(0, "PmenuKindSnippet", { fg = c.orange })
vim.api.nvim_set_hl(0, "CmpItemAbbr", { fg = c.fg })
vim.api.nvim_set_hl(0, "CmpItemAbbrMatch", { fg = c.blue, bold = true })
vim.api.nvim_set_hl(0, "CmpItemMenu", { fg = c.fg_dim })
vim.api.nvim_set_hl(0, "CmpItemKind", { fg = c.blue })
vim.api.nvim_set_hl(0, "LspDiagnosticsFloatingError", { fg = c.red })
vim.api.nvim_set_hl(0, "LspDiagnosticsFloatingWarning", { fg = c.orange })
vim.api.nvim_set_hl(0, "LspDiagnosticsFloatingInformation", { fg = c.blue })
vim.api.nvim_set_hl(0, "LspDiagnosticsFloatingHint", { fg = c.green })
vim.api.nvim_set_hl(0, "TroubleNormal", { bg = c.bg_alt })
vim.api.nvim_set_hl(0, "TroubleText", { fg = c.fg })
vim.api.nvim_set_hl(0, "TodoBgTODO", { bg = c.orange, fg = c.fg })
vim.api.nvim_set_hl(0, "TodoBgFIXME", { bg = c.red, fg = c.fg })
vim.api.nvim_set_hl(0, "TodoBgHACK", { bg = c.purple, fg = c.fg })
vim.api.nvim_set_hl(0, "TodoBgWARN", { bg = c.yellow, fg = c.bg })
vim.api.nvim_set_hl(0, "TodoBgNOTE", { bg = c.blue, fg = c.fg })
vim.api.nvim_set_hl(0, "TodoBgTEST", { bg = c.green, fg = c.fg })
vim.api.nvim_set_hl(0, "Ignore", { fg = c.fg_mute })
vim.api.nvim_set_hl(0, "WildMenu", { bg = c.selection, fg = c.fg })
vim.api.nvim_set_hl(0, "TabLine", { bg = c.bg_dark, fg = c.fg_mute })
vim.api.nvim_set_hl(0, "TabLineFill", { bg = c.bg_dark })
vim.api.nvim_set_hl(0, "TabLineSel", { bg = c.bg_alt, fg = c.fg })
vim.api.nvim_set_hl(0, "Substitute", { bg = c.selection })
vim.api.nvim_set_hl(0, "NvimTreeNormal", { bg = c.bg, fg = c.fg })
vim.api.nvim_set_hl(0, "NvimTreeWinSeparator", { bg = c.bg, fg = c.border })
vim.api.nvim_set_hl(0, "NvimTreeIndentMarker", { fg = c.border })
vim.api.nvim_set_hl(0, "User1", { fg = c.bg_alt, bg = c.green })
vim.api.nvim_set_hl(0, "User2", { fg = c.bg_alt, bg = c.blue })
vim.api.nvim_set_hl(0, "User3", { fg = c.bg_alt, bg = c.purple })
vim.api.nvim_set_hl(0, "User4", { fg = c.bg_alt, bg = c.orange })
vim.api.nvim_set_hl(0, "User5", { fg = c.bg_alt, bg = c.pink })

-- ═══════════════════════════════════════════════════════════════════════════════
-- SNACKS PICKER HIGHLIGHTS
-- ═══════════════════════════════════════════════════════════════════════════════
vim.api.nvim_set_hl(0, "SnacksPickerNormal", { bg = c.bg_alt, fg = c.fg })
vim.api.nvim_set_hl(0, "SnacksPickerBorder", { bg = c.bg_alt, fg = c.border })
vim.api.nvim_set_hl(0, "SnacksPickerTitle", { bg = c.bg_alt, fg = c.fg, bold = true })
-- Path/Directorio en verde
vim.api.nvim_set_hl(0, "SnacksPickerFile", { fg = c.fg })
vim.api.nvim_set_hl(0, "SnacksPickerDirectory", { fg = c.green })
vim.api.nvim_set_hl(0, "SnacksPickerDir", { fg = c.green })
vim.api.nvim_set_hl(0, "SnacksPickerDelim", { fg = c.fg_mute })
vim.api.nvim_set_hl(0, "SnacksPickerPathHidden", { fg = c.fg_mute })
vim.api.nvim_set_hl(0, "SnacksPickerPathIgnored", { fg = c.fg_mute })
vim.api.nvim_set_hl(0, "SnacksPickerFileTxt", { fg = c.fg })
vim.api.nvim_set_hl(0, "SnacksPickerPrompt", { bg = c.bg_alt, fg = c.blue })
vim.api.nvim_set_hl(0, "SnacksPickerInput", { bg = c.bg_alt, fg = c.fg })
vim.api.nvim_set_hl(0, "SnacksPickerSelection", { bg = c.selection, fg = c.fg })
vim.api.nvim_set_hl(0, "SnacksPickerMatch", { fg = c.green, bold = true })
vim.api.nvim_set_hl(0, "SnacksPickerIcon", { fg = c.cyan })
vim.api.nvim_set_hl(0, "SnacksPickerDirIcon", { fg = c.green })
vim.api.nvim_set_hl(0, "SnacksPickerGitIcon", { fg = c.green })
vim.api.nvim_set_hl(0, "SnacksPickerGitStatus", { fg = c.fg_mute })
vim.api.nvim_set_hl(0, "SnacksPickerList", { bg = c.bg_alt })
vim.api.nvim_set_hl(0, "SnacksPickerListEntry", { fg = c.fg })
