-- ═══════════════════════════════════════════════════════════════════════════════
-- Colorscheme - Trae Dark (sobre base Kanagawa Wave)
-- Paleta: #32F08C verde · #38B0F0 azul · #A07AEF violeta · #2DD4BF teal
--         #F05A72 rojo · #EDD040 amarillo · #E87AAC rosa · #F09040 naranja
--         bg: #0A0E14  fg: #C5D8EA
-- ═══════════════════════════════════════════════════════════════════════════════

return {
  {
    "rebelot/kanagawa.nvim",
    priority = 1000,
    opts = {
      compile = false,
      undercurl = true,
      commentStyle = { italic = true },
      functionStyle = {},
      keywordStyle = { italic = true },
      statementStyle = { bold = true },
      typeStyle = {},
      transparent = true,
      dimInactive = false,
      terminalColors = true,
      theme = "wave",
      background = {
        dark = "wave",
        light = "lotus",
      },
      colors = {
        palette = {
          sumiInk0      = "#080c12",
          sumiInk1      = "#0a0e14",
          sumiInk2      = "#0d1219",
          sumiInk3      = "#0f1520",
          sumiInk4      = "#162030",
          sumiInk5      = "#1e3048",
          sumiInk6      = "#2a3d55",
          fujiWhite     = "#c5d8ea",
          oldWhite      = "#a8c0d5",
          fujiGray      = "#4a6070",
          springGreen   = "#32f08c",
          autumnGreen   = "#32f08c",
          waveAqua1     = "#2dd4bf",
          waveAqua2     = "#50e8dc",
          crystalBlue   = "#38b0f0",
          springBlue    = "#60c8f8",
          oniViolet     = "#a07aef",
          oniViolet2    = "#bf9af8",
          springViolet1 = "#7a9ab8",
          springViolet2 = "#a07aef",
          carpYellow    = "#edd040",
          boatYellow1   = "#f09040",
          boatYellow2   = "#f0b060",
          peachRed      = "#f05a72",
          samuraiRed    = "#f05a72",
          autumnRed     = "#f07a8a",
          suraBright    = "#f05a72",
          autumnYellow  = "#edd040",
          dragonBlack0  = "#080c12",
          dragonBlack1  = "#0a0e14",
          dragonBlack2  = "#0d1219",
          dragonBlack3  = "#0f1520",
          dragonBlack4  = "#162030",
          dragonBlack5  = "#1e3048",
          dragonBlack6  = "#2a3d55",
          dragonWhite   = "#c5d8ea",
          dragonGreen   = "#32f08c",
          dragonGreen2  = "#50f8a0",
          dragonBlue    = "#38b0f0",
          dragonBlue2   = "#60c8f8",
          dragonPink    = "#e87aac",
          dragonOrange  = "#f09040",
          dragonOrange2 = "#f0b060",
          dragonGray    = "#4a6070",
          dragonGray2   = "#7a9ab8",
          dragonGray3   = "#a8c0d5",
          dragonViolet  = "#a07aef",
          dragonRed     = "#f07a8a",
          dragonTeal    = "#2dd4bf",
          dragonAqua    = "#50e8dc",
          dragonYellow  = "#edd040",
          waveBlue1     = "#1e3048",
          waveBlue2     = "#2a3d55",
          winterGreen   = "#0e2218",
          winterYellow  = "#1e2a10",
          winterRed     = "#1e1020",
          winterBlue    = "#0f1520",
          katanaGray    = "#2a3d55",
        },
      },
      overrides = function(colors)
        return {
          CursorLine   = { bg = "#0f1a28" },
          CursorLineNr = { fg = "#32f08c", bold = true },
          LineNr       = { fg = "#2a3d55" },
          WinSeparator = { fg = "#2a3d55" },
          VertSplit    = { fg = "#2a3d55" },
          StatusLine   = { bg = "#0f1520", fg = "#c5d8ea" },
          StatusLineNC = { bg = "#0a0e14", fg = "#4a6070" },
          TabLine      = { bg = "#0f1520", fg = "#4a6070" },
          TabLineSel   = { bg = "#1e3048", fg = "#32f08c", bold = true },
          TabLineFill  = { bg = "#0a0e14" },
          TelescopeNormal        = { bg = "#0f1520", fg = "#c5d8ea" },
          TelescopeBorder        = { fg = "#2a3d55", bg = "#0f1520" },
          TelescopePromptBorder  = { fg = "#32f08c", bg = "#0f1520" },
          TelescopeSelection     = { bg = "#1e3048" },
          TelescopeMatching      = { fg = "#32f08c", bold = true },
          Pmenu      = { bg = "#0f1520", fg = "#c5d8ea" },
          PmenuSel   = { bg = "#1e3048", fg = "#c5d8ea" },
          PmenuThumb = { bg = "#32f08c" },
          DiagnosticError = { fg = "#f05a72" },
          DiagnosticWarn  = { fg = "#edd040" },
          DiagnosticInfo  = { fg = "#38b0f0" },
          DiagnosticHint  = { fg = "#2dd4bf" },
          DiagnosticVirtualTextError = { fg = "#f05a72", bg = "#1e1020" },
          DiagnosticVirtualTextWarn  = { fg = "#edd040", bg = "#1a1a10" },
          DiffAdd    = { bg = "#0e2218" },
          DiffChange = { bg = "#0e1a2a" },
          DiffDelete = { bg = "#1e1020" },
          DiffText   = { bg = "#1e3048" },
          Search    = { bg = "#1e3048", fg = "#edd040" },
          IncSearch = { bg = "#32f08c", fg = "#0a0e14" },
          CurSearch = { bg = "#32f08c", fg = "#0a0e14" },
          IblIndent = { fg = "#162030" },
          IblScope  = { fg = "#2a3d55" },
        }
      end,
    },
  },
  {
    "LazyVim/LazyVim",
    opts = {
      colorscheme = "kanagawa",
    },
  },
  { "catppuccin", enabled = false },
  { "tokyonight", enabled = false },
}
